#ifndef SYSTEMUS_CONFIG_H
#define SYSTEMUS_CONFIG_H

#include <QtCore/qglobal.h>

#define SYSTEMUS_VERSION_MAJOR "1"
#define SYSTEMUS_VERSION_MINOR "2"
#define SYSTEMUS_VERSION_PATCH "0"

#define SYSTEMUS_VERSION SYSTEMUS_VERSION_CHECK(SYSTEMUS_VERSION_MAJOR, SYSTEMUS_VERSION_MINOR, SYSTEMUS_VERSION_PATCH)
#define SYSTEMUS_VERSION_CHECK QT_VERSION_CHECK

#define SYSTEMUS_VERSION_STR "1.2.0"

#ifdef QT_DEBUG
#   define SYSTEMUS_DEBUG
#endif

#define SYSTEMUS_CONNECTION "Systemus"

#endif // SYSTEMUS_CONFIG_H
