#define SYSTEMUS_UPPERCASE_a A
#define SYSTEMUS_UPPERCASE_b B
#define SYSTEMUS_UPPERCASE_c C
#define SYSTEMUS_UPPERCASE_d D
#define SYSTEMUS_UPPERCASE_e E
#define SYSTEMUS_UPPERCASE_f F
#define SYSTEMUS_UPPERCASE_g G
#define SYSTEMUS_UPPERCASE_h H
#define SYSTEMUS_UPPERCASE_i I
#define SYSTEMUS_UPPERCASE_j J
#define SYSTEMUS_UPPERCASE_k K
#define SYSTEMUS_UPPERCASE_l L
#define SYSTEMUS_UPPERCASE_m M
#define SYSTEMUS_UPPERCASE_n N
#define SYSTEMUS_UPPERCASE_o O
#define SYSTEMUS_UPPERCASE_p P
#define SYSTEMUS_UPPERCASE_q Q
#define SYSTEMUS_UPPERCASE_r R
#define SYSTEMUS_UPPERCASE_s S
#define SYSTEMUS_UPPERCASE_t T
#define SYSTEMUS_UPPERCASE_u U
#define SYSTEMUS_UPPERCASE_v V
#define SYSTEMUS_UPPERCASE_w W
#define SYSTEMUS_UPPERCASE_x X
#define SYSTEMUS_UPPERCASE_y Y
#define SYSTEMUS_UPPERCASE_z Z

#define SYSTEMUS_CONCATENATE_DETAIL(x, y) x##y
#define SYSTEMUS_CONCATENATE(x, y) SYSTEMUS_CONCATENATE_DETAIL(x, y)

#define SYSTEMUS_CAPITALIZE_FIRST_LETTER(name) SYSTEMUS_CONCATENATE(SYSTEMUS_UPPERCASE_, name)

