#ifndef SYSTEMUS_WIDGETS_GLOBAL_H
#define SYSTEMUS_WIDGETS_GLOBAL_H

#include <SystemusCore/global.h>

#ifdef SYSTEMUS_SHARED
#   ifdef SYSTEMUS_WIDGETS_BUILD
#       define SYSTEMUS_WIDGETS_EXPORT Q_DECL_EXPORT
#   else
#       define SYSTEMUS_WIDGETS_EXPORT Q_DECL_IMPORT
#   endif
#else
#   define SYSTEMUS_WIDGETS_EXPORT
#endif


#endif // SYSTEMUS_WIDGETS_GLOBAL_H
